version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/docker-publish
  docker-publish: circleci/docker-publish@0.1.3
workflows:

  # This workflow will be run on all branches but master (to test)
  build_without_publishing_job:
    jobs:
      - docker-publish/publish:
          image: srcc/smanage
          deploy: false
          filters:
            branches:
              ignore: 
                - master

  # This workflow will deploy images on merge to master only
  docker_with_lifecycle:
    jobs:
      - docker-publish/publish:
          image: srcc/smanage
          tag: latest
          filters:
            branches:
             only: master
      - docker-publish/publish:
          image: vanessa/smanage
          filters:
            branches:
             only: master
